module.exports = {
  apps: [
    {
      name: 'ccc',
      script: 'npx',
      args: 'tsx server.ts',
      cwd: __dirname,
      env: {
        NODE_ENV: 'production',
        PORT: '8347',
      },
      watch: false,
      max_memory_restart: '500M',
      error_file: '/home/chipdev/.ccc/logs/ccc-error.log',
      out_file: '/home/chipdev/.ccc/logs/ccc-out.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'ccc-discord-bot',
      script: 'npx',
      args: 'tsx discord-bot.ts',
      cwd: __dirname,
      env: {
        NODE_ENV: 'production',
        CCC_URL: 'http://localhost:8347',
        BOT_PORT: '8348',
      },
      watch: false,
      max_memory_restart: '200M',
      error_file: '/home/chipdev/.ccc/logs/bot-error.log',
      out_file: '/home/chipdev/.ccc/logs/bot-out.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'ccc-slack-poller',
      script: 'npx',
      args: 'tsx slack-poller.ts',
      cwd: __dirname,
      env: {
        NODE_ENV: 'production',
        CCC_URL: 'http://localhost:8347',
      },
      watch: false,
      max_memory_restart: '200M',
      error_file: '/home/chipdev/.ccc/logs/slack-error.log',
      out_file: '/home/chipdev/.ccc/logs/slack-out.log',
      merge_logs: true,
      time: true,
    },
  ],
}
